from datasets import make_irm_friedman
from datasets import make_plr_fingerhut2018
from datasets import make_irm_farell2021
from doubleml_skorch_api import NeuralNetRegressorDoubleML
from doubleml_skorch_api import NeuralNetRegressorXdoubleML
from simulation_base_class import simulation_study