from setuptools import setup
setup(
    name='DMLSim',
    packages=['dml_sim', 'dml_nn', 'dml_emb'],
    version='0.2.1',
    description='package to run DoubleML simulation studies and use Neural Networks approaches.',
    author=['Sundermann, Moritz <moritz.sundermann@studium.uni-hamburg.de>', 
            'Teichert-Kluge, Jan <jan.teichert-kluge@studium.uni-hamburg.de>'],
    install_requires=['DoubleML',
                      'joblib',
                      'matplotlib',
                      'numpy',
                      'openpyxl',
                      'pandas',
                      'Pillow',
                      'python-dateutil',
                      'scikit-learn',
                      'scipy=1.7.3',
                      'seaborn',
                      'skorch',
                      'statsmodels',
                      'torch',
                      'tqdm',
                      'transformers'],
     license='MIT'
)
